// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOUfp0BArUFJ9IfGkaVt2_57oNqAJF-c',
    appId: '1:420360693952:android:60ecc98834f7c9755de525',
    messagingSenderId: '420360693952',
    projectId: 'mynotes-sergepro-project',
    databaseURL:
        'https://mynotes-sergepro-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-sergepro-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACqFsMVS19jMZKg2K7-qxY-e_xNJBZzZI',
    appId: '1:420360693952:ios:d4fe293380d700b35de525',
    messagingSenderId: '420360693952',
    projectId: 'mynotes-sergepro-project',
    databaseURL:
        'https://mynotes-sergepro-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-sergepro-project.appspot.com',
    iosClientId:
        '420360693952-ndcpabprcp7j84f8731puo5qm7asih6h.apps.googleusercontent.com',
    iosBundleId: 'com.jam.mynotes',
  );
}
